"use client";

import { useEffect, useState } from "react";
import { Sparkles, ArrowRight, Loader2, Target } from "lucide-react";
import { Button, IconOrb, SectionLabel } from "./primitives";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";

export function PredictiveNextSteps({ caseId }: { caseId: string }) {
  const [steps, setSteps] = useState<{ id: string; text: string; rationale: string }[] | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchSteps() {
      try {
        const res = await fetch("/api/ai/predict-steps", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ caseId }),
        });
        const data = await res.json();
        setSteps(data.steps || []);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    }
    fetchSteps();
  }, [caseId]);

  return (
    <div className="glass rounded-3xl p-5 border border-hairline relative overflow-hidden">
      {/* Decorative background glow */}
      <div className="absolute -top-10 -right-10 w-40 h-40 bg-teal-500/10 blur-3xl rounded-full pointer-events-none" />
      
      <div className="flex items-center gap-3 mb-4">
        <IconOrb tone="teal" size="sm">
          <Sparkles className="h-4 w-4" />
        </IconOrb>
        <div>
          <h3 className="font-semibold text-foreground leading-none">AI Predictive Next Steps</h3>
          <p className="text-[10px] uppercase tracking-widest text-muted-foreground mt-1">Generated by SCRB Copilot</p>
        </div>
      </div>

      <AnimatePresence mode="wait">
        {loading ? (
          <motion.div 
            key="loading"
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            exit={{ opacity: 0 }}
            className="flex flex-col items-center justify-center py-6 text-muted-foreground"
          >
            <Loader2 className="h-5 w-5 animate-spin mb-2" />
            <span className="text-xs">Analyzing case dossier...</span>
          </motion.div>
        ) : steps && steps.length > 0 ? (
          <motion.div 
            key="content"
            initial={{ opacity: 0, y: 10 }} 
            animate={{ opacity: 1, y: 0 }}
            className="space-y-3 relative z-10"
          >
            {steps.map((step, idx) => (
              <div key={idx} className="group relative flex items-start gap-3 rounded-2xl bg-surface-2/50 p-3 hover:bg-surface-2 transition-colors border border-transparent hover:border-hairline">
                <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-surface shadow-sm text-xs font-semibold text-foreground">
                  {idx + 1}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-foreground">{step.text}</p>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-1 group-hover:line-clamp-none transition-all">{step.rationale}</p>
                </div>
                <button className="opacity-0 group-hover:opacity-100 transition-opacity p-1 hover:bg-surface rounded-full shrink-0 text-teal-600">
                  <ArrowRight className="h-4 w-4" />
                </button>
              </div>
            ))}
          </motion.div>
        ) : (
          <motion.div key="empty" className="text-sm text-muted-foreground py-4">
            No predictive steps available.
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
