/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppHotspotsRouteImport } from './routes/_app/hotspots'
import { Route as AppFirUploadRouteImport } from './routes/_app/fir-upload'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCasesRouteImport } from './routes/_app/cases'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app/cases.$caseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppHotspotsRoute = AppHotspotsRouteImport.update({
  id: '/hotspots',
  path: '/hotspots',
  getParentRoute: () => AppRoute,
} as any)
const AppFirUploadRoute = AppFirUploadRouteImport.update({
  id: '/fir-upload',
  path: '/fir-upload',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AppCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof AppCasesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/fir-upload': typeof AppFirUploadRoute
  '/hotspots': typeof AppHotspotsRoute
  '/network': typeof AppNetworkRoute
  '/settings': typeof AppSettingsRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof AppCasesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/fir-upload': typeof AppFirUploadRoute
  '/hotspots': typeof AppHotspotsRoute
  '/network': typeof AppNetworkRoute
  '/settings': typeof AppSettingsRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/cases': typeof AppCasesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fir-upload': typeof AppFirUploadRoute
  '/_app/hotspots': typeof AppHotspotsRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/dashboard'
    | '/fir-upload'
    | '/hotspots'
    | '/network'
    | '/settings'
    | '/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/dashboard'
    | '/fir-upload'
    | '/hotspots'
    | '/network'
    | '/settings'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/cases'
    | '/_app/dashboard'
    | '/_app/fir-upload'
    | '/_app/hotspots'
    | '/_app/network'
    | '/_app/settings'
    | '/_app/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hotspots': {
      id: '/_app/hotspots'
      path: '/hotspots'
      fullPath: '/hotspots'
      preLoaderRoute: typeof AppHotspotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fir-upload': {
      id: '/_app/fir-upload'
      path: '/fir-upload'
      fullPath: '/fir-upload'
      preLoaderRoute: typeof AppFirUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppCasesRoute
    }
  }
}

interface AppCasesRouteChildren {
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
}

const AppCasesRouteChildren: AppCasesRouteChildren = {
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
}

const AppCasesRouteWithChildren = AppCasesRoute._addFileChildren(
  AppCasesRouteChildren,
)

interface AppRouteChildren {
  AppCasesRoute: typeof AppCasesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFirUploadRoute: typeof AppFirUploadRoute
  AppHotspotsRoute: typeof AppHotspotsRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRoute: AppCasesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFirUploadRoute: AppFirUploadRoute,
  AppHotspotsRoute: AppHotspotsRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
